---
variables:
  STAGING_URL: dev.staging.torproject.net

include:
  - project: tpo/tpa/ci-templates
    file:
      - static-shim-deploy.yml

build:
  image: docker.io/node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

# override pages job defined in templates
# needs to build with specific --baseURL
pages:
  image: docker.io/node:latest
  variables:
    GIT_STRATEGY: fetch
  script:
    - npm install
    - npm run build -- --baseURL $CI_PAGES_URL
  dependencies: []
