---
variables:
  STAGING_URL: dev.staging.torproject.net

build:
  image: debian:stable-slim
  stage: build
  before_script:
    - apt update && apt-get install --no-install-recommends -y hugo
  script:
    - hugo
  artifacts:
    paths:
      - public

pages:
  extends: build
  stage: deploy
  script:
    - hugo --baseURL $CI_PAGES_URL
  artifacts: ~
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
