---
variables:
  STAGING_URL: dev.staging.torproject.net

build:
  image: registry.gitlab.com/pages/hugo/hugo_extended
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - public

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended
  stage: deploy
  script:
    - hugo --baseURL $CI_PAGES_URL
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
