variables:
  SITE_URL: "dev.torproject.org"
  TRANSLATION_BRANCH: "dev-portal"

include:
  - project: tpo/tpa/ci-templates
    file: lektor.yml
  - project: tpo/tpa/ci-templates
    file: static-shim-deploy.yml
