---
variables:
  STAGING_URL: dev.staging.torproject.net

build:
  image: docker.io/node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

pages:
  image: docker.io/node:latest
  stage: deploy
  script:
    - npm install
    - npm run build -- --baseURL $CI_PAGES_URL
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
