[[main]]
  name = "Docs"
  url = "/docs/understanding-tor/overview/"
  weight = 10

[[main]]
  name = "About"
  url = "https://www.torproject.org/about/history/"
  weight = "1"

[[main]]
  name = "Support"
  url = "https://support.torproject.org/"
  weight = "2"

[[main]]
  name = "Community"
  url = "https://community.torproject.org/"
  weight = "3"

[[main]]
  name = "Blog"
  url = "https://blog.torproject.org"
  weight = "4"

[[main]]
  name = "Donate"
  url = "https://donate.torproject.org"
  weight = "5"

[[social]]
  name = "GitLab"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-gitlab\"><path d=\"M22.65 14.39L12 22.13 1.35 14.39a.84.84 0 0 1-.3-.94l1.22-3.78 2.44-7.51A.42.42 0 0 1 4.82 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.49h8.1l2.44-7.51A.42.42 0 0 1 18.6 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.51L23 13.45a.84.84 0 0 1-.35.94z\"></path></svg>"
  url = "https://gitlab.torproject.org/tpo/web/dev"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/torproject"
  weight = 20

 [[footer]]
   name = "Privacy"
   url = "/privacy-policy/"
   weight = 10
